### ISSUE TITLE
script path raising TypeError for custom script

### ISSUE THREAD

**Issue by tnsardesai** [that-recsys-lab/librec-auto#3]
Hi,

I have been using librec-auto for my MS capstone project and found a bug for reading custom scripts.

Say the xml is as follows 
`
<rerank action="no-parse">
	<script lang="python3" src="./scripts">
		<script-name>custom-script.py</script-name>
		<param name="lambda">0.4</param>
	</script>
</rerank>
`

This will return

> File "/Users/tanmay/.virtualenvs/capstone/lib/python3.7/site-packages/librec_auto/util/utils.py", line 162, in get_script_path
    return script_path / script_xml['script-name']
TypeError: unsupported operand type(s) for /: 'str' and 'str'

Same error when you don't pass src attribute.

Error comes from https://github.com/that-recsys-lab/librec-auto/blob/master/librec_auto/util/utils.py#L161.

**Comment by rburke2233** [comment]
Install version 0.1.4 for these fixes.
