### ISSUE TITLE
Documentation references to other "recommendation systems"

### ISSUE THREAD

**Issue by BrandonKMLee** [that-recsys-lab/librec-auto#46]
Since this is based on LibRec, these libraries can also be referenced.
- Python/SciKit based https://github.com/NicolasHug/Surprise
- Go basedhttps://github.com/zhenghaoz/gorse
- Mendeley https://github.com/Mendeley/mrec

**Comment by rburke2233** [comment]
Our next release (probably v0.2.3) will contain code for interfacing to non LibRec libraries. We will ship with the MS Recommenders library (https://github.com/microsoft/recommenders) but the facility will be there to incorporate whatever additional libraries you want to use.
