### ISSUE TITLE
When no param are passed to rerank script it fails to run

### ISSUE THREAD

**Issue by tnsardesai** [that-recsys-lab/librec-auto#5]
Say we have the following xml
`
	<rerank action="no-parse">
		<script lang="python3">
			<script-name>custom-rerank.py</script-name>
		</script>
	</rerank>
`
We get the following error
> File "/Users/tanmay/.virtualenvs/capstone/lib/python3.7/site-packages/librec_auto/cmd/rerank_cmd.py", line 43, in execute
    param_spec = create_param_spec(script_data[1])
  File "/Users/tanmay/.virtualenvs/capstone/lib/python3.7/site-packages/librec_auto/util/utils.py", line 167, in create_param_spec
    return [f'--{key}={val}' for key, val in param_dict.items()]
AttributeError: 'NoneType' object has no attribute 'items'

This is happening because we have no param for the script in our xml which is entirely possible for some rerank methods. Current workaround is to pass a dummy param which the rerank script ignores :)

Lines in question:
https://github.com/that-recsys-lab/librec-auto/blob/5361bd125f80098eca7ee24e6dd426c866bfc278/librec_auto/cmd/rerank_cmd.py#L42

https://github.com/that-recsys-lab/librec-auto/blob/5361bd125f80098eca7ee24e6dd426c866bfc278/librec_auto/util/utils.py#L166

**Comment by rburke2233** [comment]
Thanks for your interest in librec-auto. Please take a look at the "script-fixes" branch and the following two files:

librec_auto/cmd/post_cmd.py
librec_auto/util/utils.py

I believe both bugs are fixed here. Please check by substituting these files for the corresponding ones in your installation. It will take us a couple of days to produce a new release and upload to pypi for easy update. Thanks.

**Comment by rburke2233** [comment]
Install version 0.1.4 to get these fixes.
